<?php

$bdd = array(
    array("nom"=>"Geraldine Howard","pays"=>"Brunei",
            "marié"=>1,"naissance"=>"02/04/1981"),
    array("nom"=>"Candice Barnett","pays"=>"Niger",
            "marié"=>0,"naissance"=>"16/10/1972"),
    array("nom"=>"Denise Sherman","pays"=>"Uzbekistan",
            "marié"=>1,"naissance"=>"23/09/1965"),
    array("nom"=>"Nigel Donovan","pays"=>"Argentina",
            "marié"=>0,"naissance"=>"22/07/1984"),
    array("nom"=>"Kerry Richmond","pays"=>"Guinea-Bissau",
            "marié"=>1,"naissance"=>"01/03/1987"),
    array("nom"=>"Giselle Flowers","pays"=>"Nigeria",
            "marié"=>0,"naissance"=>"03/11/1974"),
    array("nom"=>"Theodore Lucas","pays"=>"Trinidad and Tobago",
            "marié"=>1,"naissance"=>"31/12/1996"),
    array("nom"=>"Lael Bass","pays"=>"Belarus",
            "marié"=>0,"naissance"=>"05/08/1974"),
    array("nom"=>"Amy Ndiaye","pays"=>"Senegal",
            "marié"=>0,"naissance"=>"12/05/1980"),
    array("nom"=>"Axel Roberson","pays"=>"Comoros",
            "marié"=>0,"naissance"=>"10/04/1973"),
    array("nom"=>"Jescie Robbins","pays"=>"Luxembourg",
            "marié"=>1,"naissance"=>"29/12/1985"),
    array("nom"=>"Clarke Randolph","pays"=>"Jamaica",
            "marié"=>0,"naissance"=>"15/01/1992"),
    array("nom"=>"Keane Conley","pays"=>"Palau",
            "marié"=>1,"naissance"=>"04/12/1968"),
    array("nom"=>"Chancellor Frazier","pays"=>"Tokelau",
            "marié"=>0,"naissance"=>"14/01/1969"),
    array("nom"=>"Arthur Simon","pays"=>"Turkmenistan",
            "marié"=>0,"naissance"=>"24/08/1980"),
    array("nom"=>"Molly Sears","pays"=>"Belarus",
            "marié"=>1,"naissance"=>"22/09/1976"),
    array("nom"=>"Elizabeth Haynes","pays"=>"Georgia",
            "marié"=>1,"naissance"=>"05/03/1972"),
    array("nom"=>"Jarrod Rios","pays"=>"Saint Martin",
            "marié"=>1,"naissance"=>"11/11/1994"),
    array("nom"=>"Emerson Rosa","pays"=>"Laos",
            "marié"=>1,"naissance"=>"21/12/1988"),
    array("nom"=>"Jorden Mccall","pays"=>"Bahrain",
            "marié"=>1,"naissance"=>"02/08/1970"),
    array("nom"=>"Stephen Vasquez","pays"=>"Palau",
            "marié"=>0,"naissance"=>"24/06/1988"),
    array("nom"=>"Martin Bishop","pays"=>"Bolivia",
            "marié"=>1,"naissance"=>"28/01/1967"),
    array("nom"=>"Rama Siga","pays"=>"Senegal",
            "marié"=>0,"naissance"=>"19/11/1994"),
    array("nom"=>"Brody Christian","pays"=>"Burkina Faso",
            "marié"=>1,"naissance"=>"07/03/1977"),
    array("nom"=>"Ruth Roman","pays"=>"Solomon Islands",
            "marié"=>1,"naissance"=>"24/07/1978"),
    array("nom"=>"Gemma Guy","pays"=>"Lithuania",
            "marié"=>0,"naissance"=>"01/10/1989"),
    array("nom"=>"Elijah Copeland","pays"=>"Maldives",
            "marié"=>1,"naissance"=>"26/05/1970"),
    array("nom"=>"Lance Curry","pays"=>"Belarus",
            "marié"=>0,"naissance"=>"31/05/1994"),
    array("nom"=>"Forrest Battle","pays"=>"Korea, North",
            "marié"=>0,"naissance"=>"05/02/1971"),
    array("nom"=>"Eric Glass","pays"=>"Lebanon",
            "marié"=>0,"naissance"=>"19/03/1987"),
    array("nom"=>"Brent Mercado","pays"=>"Nepal",
            "marié"=>1,"naissance"=>"17/01/1995"),
    array("nom"=>"Clayton Poole","pays"=>"Mali",
            "marié"=>0,"naissance"=>"27/04/1988"),
    array("nom"=>"Rhoda Meyers","pays"=>"Cambodia",
            "marié"=>1,"naissance"=>"19/02/1983"),
    array("nom"=>"Sokhna Khoni","pays"=>"Senegal",
            "marié"=>1,"naissance"=>"04/10/1989"),
    array("nom"=>"Heather Acosta","pays"=>"Samoa",
            "marié"=>1,"naissance"=>"21/01/1974"),
    array("nom"=>"Martin Allison","pays"=>"American Samoa",
            "marié"=>0,"naissance"=>"27/11/1996"),
    array("nom"=>"Damon Mills","pays"=>"Saint Martin",
            "marié"=>0,"naissance"=>"10/04/1985"),
    array("nom"=>"Baxter Jacobs","pays"=>"United States",
            "marié"=>1,"naissance"=>"20/04/1976"),
    array("nom"=>"Jayme Herrera","pays"=>"Botswana",
            "marié"=>0,"naissance"=>"13/02/1973"),
    array("nom"=>"Justin Sparks","pays"=>"Austria",
            "marié"=>0,"naissance"=>"04/03/1986"),
    array("nom"=>"Phillip Macias","pays"=>"Martinique",
            "marié"=>1,"naissance"=>"24/09/1969"),
    array("nom"=>"Althea Bonner","pays"=>"Burkina Faso",
            "marié"=>0,"naissance"=>"02/08/1986"),
    array("nom"=>"Melinda Nolan","pays"=>"Jersey",
            "marié"=>0,"naissance"=>"14/03/1983"),
    array("nom"=>"Salvador King","pays"=>"Iraq",
            "marié"=>0,"naissance"=>"01/10/1976"),
    array("nom"=>"Allistair Winters","pays"=>"Kuwait",
            "marié"=>1,"naissance"=>"19/03/1987"),
    array("nom"=>"Roary Golden","pays"=>"French Guiana",
            "marié"=>1,"naissance"=>"19/09/1995"),
    array("nom"=>"Idola Cantrell","pays"=>"Senegal",
            "marié"=>1,"naissance"=>"16/07/1992"),
    array("nom"=>"Chadwick Conrad","pays"=>"Puerto Rico",
            "marié"=>1,"naissance"=>"27/02/1997"),
    array("nom"=>"Kiona Huber","pays"=>"Czech Republic",
            "marié"=>1,"naissance"=>"26/10/1988"),
    array("nom"=>"Wesley Sloan","pays"=>"South Africa",
            "marié"=>1,"naissance"=>"01/12/1991"),
    array("nom"=>"Timothy Hall","pays"=>"Estonia",
            "marié"=>0,"naissance"=>"08/08/1991"),
    array("nom"=>"Haviva Peterson","pays"=>"Romania",
            "marié"=>1,"naissance"=>"12/01/1974"),
    array("nom"=>"Sylvia Cameron","pays"=>"Myanmar",
            "marié"=>0,"naissance"=>"27/01/1970"),
    array("nom"=>"Vernon Russell","pays"=>"Micronesia",
            "marié"=>1,"naissance"=>"10/02/1975"),
    array("nom"=>"Kadeem David","pays"=>"Morocco",
            "marié"=>0,"naissance"=>"13/12/1987"),
    array("nom"=>"Kylynn Odom","pays"=>"Martinique",
            "marié"=>1,"naissance"=>"01/09/1988"),
    array("nom"=>"Jolene Hopper","pays"=>"Christmas Island",
            "marié"=>0,"naissance"=>"06/04/1977"),
    array("nom"=>"Anika Foreman","pays"=>"Korea, South",
            "marié"=>1,"naissance"=>"12/02/1995"),
    array("nom"=>"Donovan Sullivan","pays"=>"Faroe Islands",
            "marié"=>1,"naissance"=>"04/01/1974"),
    array("nom"=>"Yen Stout","pays"=>"Nicaragua",
            "marié"=>0,"naissance"=>"19/09/1978"),
    array("nom"=>"Wesley Mcdonald","pays"=>"Viet Nam",
            "marié"=>0,"naissance"=>"09/07/1987"),
    array("nom"=>"Gloria English","pays"=>"Hungary",
            "marié"=>1,"naissance"=>"05/12/1965"),
    array("nom"=>"Lamar Avila","pays"=>"Chad",
            "marié"=>0,"naissance"=>"06/12/1983"),
    array("nom"=>"Barclay Hutchinson","pays"=>"Mauritania",
            "marié"=>0,"naissance"=>"29/05/1978"),
    array("nom"=>"Chaim Bond","pays"=>"Puerto Rico",
            "marié"=>1,"naissance"=>"14/07/1987"),
    array("nom"=>"Wing Carroll","pays"=>"Anguilla",
            "marié"=>1,"naissance"=>"03/11/1990"),
    array("nom"=>"Christian Sullivan","pays"=>"Libya",
            "marié"=>1,"naissance"=>"27/02/1980"),
    array("nom"=>"Inez Mathews","pays"=>"Cyprus",
            "marié"=>1,"naissance"=>"02/06/1969"),
    array("nom"=>"Gil Maldonado","pays"=>"Senegal",
        "marié"=>1,"naissance"=>"23/06/1969"),
    array("nom"=>"Darius Poole","pays"=>"Estonia",
            "marié"=>0,"naissance"=>"19/11/1992"),
    array("nom"=>"Stuart Mcdaniel","pays"=>"Uruguay",
            "marié"=>0,"naissance"=>"11/10/1995"),
    array("nom"=>"Darrel Key","pays"=>"Switzerland",
            "marié"=>1,"naissance"=>"16/02/1983"),
    array("nom"=>"Jolie Mcfarland","pays"=>"Afghanistan",
            "marié"=>1,"naissance"=>"26/12/1965"),
    array("nom"=>"Larissa Fox","pays"=>"Timor-Leste",
            "marié"=>0,"naissance"=>"01/12/1967"),
    array("nom"=>"Fitzgerald Mayo","pays"=>"Suriname",
            "marié"=>1,"naissance"=>"25/04/1970"),
    array("nom"=>"Warren Mcguire","pays"=>"Cameroon",
            "marié"=>1,"naissance"=>"19/03/1969"),
    array("nom"=>"Colin Marks","pays"=>"Honduras",
            "marié"=>1,"naissance"=>"02/05/1985"),
    array("nom"=>"Brielle Sears","pays"=>"Norway",
            "marié"=>0,"naissance"=>"27/02/1979"),
    array("nom"=>"Elaine Holman","pays"=>"Cayman Islands",
            "marié"=>1,"naissance"=>"16/06/1969"),
    array("nom"=>"Jin Bonner","pays"=>"Seychelles",
            "marié"=>0,"naissance"=>"02/09/1996"),
    array("nom"=>"Ulysses Mccullough","pays"=>"Nauru",
            "marié"=>1,"naissance"=>"16/06/1971"),
    array("nom"=>"Xerxes Mccray","pays"=>"Hungary",
            "marié"=>1,"naissance"=>"12/12/1987"),
    array("nom"=>"Kirestin Mann","pays"=>"Sweden",
            "marié"=>0,"naissance"=>"01/08/1970"),
    array("nom"=>"Allistair Ward","pays"=>"Laos",
            "marié"=>0,"naissance"=>"21/04/1977"),
    array("nom"=>"Brennan Mccarty","pays"=>"Tuvalu",
            "marié"=>0,"naissance"=>"08/11/1993"),
    array("nom"=>"Camille Fulton","pays"=>"Senegal",
            "marié"=>0,"naissance"=>"20/05/1976"),
    array("nom"=>"Leandra Serrano","pays"=>"India",
            "marié"=>1,"naissance"=>"23/12/1990"),
    array("nom"=>"Russell Zamora","pays"=>"Niger",
            "marié"=>0,"naissance"=>"10/02/1980"),
    array("nom"=>"Hermione Mcconnell","pays"=>"Philippines",
            "marié"=>0,"naissance"=>"23/09/1978"),
    array("nom"=>"Alvin Joyce","pays"=>"Comoros",
            "marié"=>1,"naissance"=>"15/01/1984"),
    array("nom"=>"Imani Goff","pays"=>"Nicaragua",
            "marié"=>1,"naissance"=>"30/01/1994"),
    array("nom"=>"Alan Hoover","pays"=>"Greenland",
            "marié"=>1,"naissance"=>"04/09/1971"),
    array("nom"=>"Robert Cantu","pays"=>"Western Sahara",
            "marié"=>1,"naissance"=>"13/10/1985")
);

echo json_encode($bdd);