<?php

$bdd = array(
    array('nom'=>'Lael Bass','nomPays'=>'Belarus',
            'majeur'=>false,'mariage'=>'05/08/2020'),
    array('nom'=>'Amy Ndiaye','nomPays'=>'Senegal',
            'majeur'=>false,'mariage'=>'12/05/2019'),
    array('nom'=>'Axel Roberson','nomPays'=>'Comoros',
            'majeur'=>false,'mariage'=>'10/04/2020'),
    array('nom'=>'Jescie Robbins','nomPays'=>'Luxembourg',
            'majeur'=>true,'mariage'=>'29/12/2019'),
    array('nom'=>'Clarke Randolph','nomPays'=>'Jamaica',
            'majeur'=>false,'mariage'=>'15/01/2019'),
    array('nom'=>'Keane Conley','nomPays'=>'Palau',
            'majeur'=>true,'mariage'=>'04/12/2020'),
    array('nom'=>'Chancellor Frazier','nomPays'=>'Tokelau',
            'majeur'=>false,'mariage'=>'14/01/2020'),
    array('nom'=>'Arthur Simon','nomPays'=>'Turkmenistan',
            'majeur'=>false,'mariage'=>'24/08/2019'),
    array('nom'=>'Molly Sears','nomPays'=>'Belarus',
            'majeur'=>true,'mariage'=>'22/09/2020'),
    array('nom'=>'Elizabeth Haynes','nomPays'=>'Georgia',
            'majeur'=>true,'mariage'=>'05/03/2020'),
    array('nom'=>'Jarrod Rios','nomPays'=>'Saint Martin',
            'majeur'=>true,'mariage'=>'11/11/2019'),
    array('nom'=>'Andoniaina Rantoson','nomPays'=>'Madagascar',
        'majeur'=>true,'mariage'=>'02/04/2019'),
    array('nom'=>'Sonny Hu Thiong Feng Piou','nomPays'=>'Tibet',
        'majeur'=>false,'mariage'=>'16/10/2020'),
    array('nom'=>'Ludovic Huguenot','nomPays'=>'France',
        'majeur'=>true,'mariage'=>'23/09/2020'),
    array('nom'=>'Gauthier Bressanin','nomPays'=>'France',
        'majeur'=>false,'mariage'=>'22/07/2019'),
    array('nom'=>'Lin Zhu','nomPays'=>'China',
        'majeur'=>true,'mariage'=>'01/03/2019'),
    array('nom'=>'Giselle Flowers','nomPays'=>'Nigeria',
        'majeur'=>false,'mariage'=>'03/11/2020'),
    array('nom'=>'Stephane Daude','nomPays'=>'France',
        'majeur'=>true,'mariage'=>'31/12/2019'),
    array('nom'=>'Emerson Rosa','nomPays'=>'Laos',
            'majeur'=>true,'mariage'=>'21/12/2019'),
    array('nom'=>'Jorden Mccall','nomPays'=>'Bahrain',
            'majeur'=>true,'mariage'=>'02/08/2020'),
    array('nom'=>'Stephen Vasquez','nomPays'=>'Palau',
            'majeur'=>false,'mariage'=>'24/06/2019'),
    array('nom'=>'Martin Bishop','nomPays'=>'Bolivia',
            'majeur'=>true,'mariage'=>'28/01/2020'),
    array('nom'=>'Rama Siga','nomPays'=>'Senegal',
            'majeur'=>false,'mariage'=>'19/11/2019'),
    array('nom'=>'Brody Christian','nomPays'=>'Burkina Faso',
            'majeur'=>true,'mariage'=>'07/03/2020'),
    array('nom'=>'Ruth Roman','nomPays'=>'Solomon Islands',
            'majeur'=>true,'mariage'=>'24/07/2020'),
    array('nom'=>'Gemma Guy','nomPays'=>'Lithuania',
            'majeur'=>false,'mariage'=>'01/10/2019'),
    array('nom'=>'Elijah Copeland','nomPays'=>'Maldives',
            'majeur'=>true,'mariage'=>'26/05/2020'),
    array('nom'=>'Lance Curry','nomPays'=>'Belarus',
            'majeur'=>false,'mariage'=>'31/05/2019'),
    array('nom'=>'Forrest Battle','nomPays'=>'Korea, North',
            'majeur'=>false,'mariage'=>'05/02/2020'),
    array('nom'=>'Eric Glass','nomPays'=>'Lebanon',
            'majeur'=>false,'mariage'=>'19/03/2019'),
    array('nom'=>'Brent Mercado','nomPays'=>'Nepal',
            'majeur'=>true,'mariage'=>'17/01/2019'),
    array('nom'=>'Clayton Poole','nomPays'=>'Mali',
            'majeur'=>false,'mariage'=>'27/04/2019'),
    array('nom'=>'Rhoda Meyers','nomPays'=>'Cambodia',
            'majeur'=>true,'mariage'=>'19/02/2019'),
    array('nom'=>'Sokhna Khoni','nomPays'=>'Senegal',
            'majeur'=>true,'mariage'=>'04/10/2019'),
    array('nom'=>'Heather Acosta','nomPays'=>'Samoa',
            'majeur'=>true,'mariage'=>'21/01/2020'),
    array('nom'=>'Martin Allison','nomPays'=>'American Samoa',
            'majeur'=>false,'mariage'=>'27/11/2019'),
    array('nom'=>'Damon Mills','nomPays'=>'Saint Martin',
            'majeur'=>false,'mariage'=>'10/04/2019'),
    array('nom'=>'Baxter Jacobs','nomPays'=>'United States',
            'majeur'=>true,'mariage'=>'20/04/2020'),
    array('nom'=>'Jayme Herrera','nomPays'=>'Botswana',
            'majeur'=>false,'mariage'=>'13/02/2020'),
    array('nom'=>'Justin Sparks','nomPays'=>'Austria',
            'majeur'=>false,'mariage'=>'04/03/2019'),
    array('nom'=>'Phillip Macias','nomPays'=>'Martinique',
            'majeur'=>true,'mariage'=>'24/09/2020'),
    array('nom'=>'Althea Bonner','nomPays'=>'Burkina Faso',
            'majeur'=>false,'mariage'=>'02/08/2019'),
    array('nom'=>'Melinda Nolan','nomPays'=>'Jersey',
            'majeur'=>false,'mariage'=>'14/03/2019'),
    array('nom'=>'Salvador King','nomPays'=>'Iraq',
            'majeur'=>false,'mariage'=>'01/10/2020'),
    array('nom'=>'Allistair Winters','nomPays'=>'Kuwait',
            'majeur'=>true,'mariage'=>'19/03/2019'),
    array('nom'=>'Roary Golden','nomPays'=>'France',
            'majeur'=>true,'mariage'=>'19/09/2019'),
    array('nom'=>'Idola Cantrell','nomPays'=>'Senegal',
            'majeur'=>true,'mariage'=>'16/07/2019'),
    array('nom'=>'Chadwick Conrad','nomPays'=>'Puerto Rico',
            'majeur'=>true,'mariage'=>'27/02/2019'),
    array('nom'=>'Kiona Huber','nomPays'=>'Czech Republic',
            'majeur'=>true,'mariage'=>'26/10/2019'),
    array('nom'=>'Wesley Sloan','nomPays'=>'South Africa',
            'majeur'=>true,'mariage'=>'01/12/2019'),
    array('nom'=>'Timothy Hall','nomPays'=>'Estonia',
            'majeur'=>false,'mariage'=>'08/08/2019'),
    array('nom'=>'Haviva Peterson','nomPays'=>'Romania',
            'majeur'=>true,'mariage'=>'12/01/2020'),
    array('nom'=>'Sylvia Cameron','nomPays'=>'Myanmar',
            'majeur'=>false,'mariage'=>'27/01/2020'),
    array('nom'=>'Vernon Russell','nomPays'=>'Micronesia',
            'majeur'=>true,'mariage'=>'10/02/2020'),
    array('nom'=>'Kadeem David','nomPays'=>'Morocco',
            'majeur'=>false,'mariage'=>'13/12/2019'),
    array('nom'=>'Kylynn Odom','nomPays'=>'Martinique',
            'majeur'=>true,'mariage'=>'01/09/2019'),
    array('nom'=>'Jolene Hopper','nomPays'=>'Christmas Island',
            'majeur'=>false,'mariage'=>'06/04/2020'),
    array('nom'=>'Anika Foreman','nomPays'=>'Korea, South',
            'majeur'=>true,'mariage'=>'12/02/2019'),
    array('nom'=>'Donovan Sullivan','nomPays'=>'Faroe Islands',
            'majeur'=>true,'mariage'=>'04/01/2020'),
    array('nom'=>'Yen Stout','nomPays'=>'Nicaragua',
            'majeur'=>false,'mariage'=>'19/09/2020'),
    array('nom'=>'Wesley Mcdonald','nomPays'=>'Viet Nam',
            'majeur'=>false,'mariage'=>'09/07/2019'),
    array('nom'=>'Gloria English','nomPays'=>'Hungary',
            'majeur'=>true,'mariage'=>'05/12/2020'),
    array('nom'=>'Lamar Avila','nomPays'=>'Chad',
            'majeur'=>false,'mariage'=>'06/12/2019'),
    array('nom'=>'Barclay Hutchinson','nomPays'=>'Mauritania',
            'majeur'=>false,'mariage'=>'29/05/2020'),
    array('nom'=>'Chaim Bond','nomPays'=>'Puerto Rico',
            'majeur'=>true,'mariage'=>'14/07/2019'),
    array('nom'=>'Wing Carroll','nomPays'=>'Anguilla',
            'majeur'=>true,'mariage'=>'03/11/2019'),
    array('nom'=>'Christian Sullivan','nomPays'=>'Libya',
            'majeur'=>true,'mariage'=>'27/02/2019'),
    array('nom'=>'Inez Mathews','nomPays'=>'Cyprus',
            'majeur'=>true,'mariage'=>'02/06/2020'),
    array('nom'=>'Gil Maldonado','nomPays'=>'Senegal',
        'majeur'=>true,'mariage'=>'23/06/2020'),
    array('nom'=>'Darius Poole','nomPays'=>'Estonia',
            'majeur'=>false,'mariage'=>'19/11/2019'),
    array('nom'=>'Stuart Mcdaniel','nomPays'=>'Uruguay',
            'majeur'=>false,'mariage'=>'11/10/2019'),
    array('nom'=>'Darrel Key','nomPays'=>'Switzerland',
            'majeur'=>true,'mariage'=>'16/02/2019'),
    array('nom'=>'Jolie Mcfarland','nomPays'=>'Afghanistan',
            'majeur'=>true,'mariage'=>'26/12/2020'),
    array('nom'=>'Larissa Fox','nomPays'=>'Timor-Leste',
            'majeur'=>false,'mariage'=>'01/12/2020'),
    array('nom'=>'Fitzgerald Mayo','nomPays'=>'Suriname',
            'majeur'=>true,'mariage'=>'25/04/2020'),
    array('nom'=>'Warren Mcguire','nomPays'=>'Cameroon',
            'majeur'=>true,'mariage'=>'19/03/2020'),
    array('nom'=>'Colin Marks','nomPays'=>'Honduras',
            'majeur'=>true,'mariage'=>'02/05/2019'),
    array('nom'=>'Brielle Sears','nomPays'=>'Norway',
            'majeur'=>false,'mariage'=>'27/02/2020'),
    array('nom'=>'Elaine Holman','nomPays'=>'Cayman Islands',
            'majeur'=>true,'mariage'=>'16/06/2020'),
    array('nom'=>'Jin Bonner','nomPays'=>'Seychelles',
            'majeur'=>false,'mariage'=>'02/09/2019'),
    array('nom'=>'Ulysses Mccullough','nomPays'=>'Nauru',
            'majeur'=>true,'mariage'=>'16/06/2020'),
    array('nom'=>'Xerxes Mccray','nomPays'=>'Hungary',
            'majeur'=>true,'mariage'=>'12/12/2019'),
    array('nom'=>'Kirestin Mann','nomPays'=>'Sweden',
            'majeur'=>false,'mariage'=>'01/08/2020'),
    array('nom'=>'Allistair Ward','nomPays'=>'Laos',
            'majeur'=>false,'mariage'=>'21/04/2020'),
    array('nom'=>'Brennan Mccarty','nomPays'=>'Tuvalu',
            'majeur'=>false,'mariage'=>'08/11/2019'),
    array('nom'=>'Camille Fulton','nomPays'=>'Senegal',
            'majeur'=>false,'mariage'=>'20/05/2020'),
    array('nom'=>'Leandra Serrano','nomPays'=>'India',
            'majeur'=>true,'mariage'=>'23/12/2019'),
    array('nom'=>'Russell Zamora','nomPays'=>'Niger',
            'majeur'=>false,'mariage'=>'10/02/2019'),
    array('nom'=>'Hermione Mcconnell','nomPays'=>'Philippines',
            'majeur'=>false,'mariage'=>'23/09/2020'),
    array('nom'=>'Alvin Joyce','nomPays'=>'Comoros',
            'majeur'=>true,'mariage'=>'15/01/2019'),
    array('nom'=>'Imani Goff','nomPays'=>'Nicaragua',
            'majeur'=>true,'mariage'=>'30/01/2019'),
    array('nom'=>'Alan Hoover','nomPays'=>'Greenland',
            'majeur'=>true,'mariage'=>'04/09/2020'),
    array('nom'=>'Robert Cantu','nomPays'=>'Western Sahara',
            'majeur'=>true,'mariage'=>'13/10/2019')
);

$listPays = [];
$i=1;
foreach ($bdd as &$person){
    if(in_array($person['nomPays'], $listPays)) {
        $person['pays'] = array_search($person['nomPays'], $listPays);
    }
    else {
        $listPays[$i] = $person['nomPays'];
        $person['pays'] = $i;
        $i++;
    }
}
unset($listPays);

echo json_encode($bdd);