<?php

$bdd = array(
    array('nom'=>'Lael Bass','nomPays'=>'Belarus',
            'marie'=>0,'naissance'=>'05/08/1974'),
    array('nom'=>'Amy Ndiaye','nomPays'=>'Senegal',
            'marie'=>0,'naissance'=>'12/05/1980'),
    array('nom'=>'Axel Roberson','nomPays'=>'Comoros',
            'marie'=>0,'naissance'=>'10/04/1973'),
    array('nom'=>'Jescie Robbins','nomPays'=>'Luxembourg',
            'marie'=>1,'naissance'=>'29/12/1985'),
    array('nom'=>'Clarke Randolph','nomPays'=>'Jamaica',
            'marie'=>0,'naissance'=>'15/01/1992'),
    array('nom'=>'Keane Conley','nomPays'=>'Palau',
            'marie'=>1,'naissance'=>'04/12/1968'),
    array('nom'=>'Chancellor Frazier','nomPays'=>'Tokelau',
            'marie'=>0,'naissance'=>'14/01/1969'),
    array('nom'=>'Arthur Simon','nomPays'=>'Turkmenistan',
            'marie'=>0,'naissance'=>'24/08/1980'),
    array('nom'=>'Molly Sears','nomPays'=>'Belarus',
            'marie'=>1,'naissance'=>'22/09/1976'),
    array('nom'=>'Elizabeth Haynes','nomPays'=>'Georgia',
            'marie'=>1,'naissance'=>'05/03/1972'),
    array('nom'=>'Jarrod Rios','nomPays'=>'Saint Martin',
            'marie'=>1,'naissance'=>'11/11/1994'),
    array('nom'=>'Andoniaina Rantoson','nomPays'=>'Madagascar',
        'marie'=>1,'naissance'=>'02/04/1981'),
    array('nom'=>'Sonny Hu Thiong Feng Piou','nomPays'=>'Tibet',
        'marie'=>0,'naissance'=>'16/10/1972'),
    array('nom'=>'Ludovic Huguenot','nomPays'=>'France',
        'marie'=>1,'naissance'=>'23/09/1965'),
    array('nom'=>'Gauthier Bressanin','nomPays'=>'France',
        'marie'=>0,'naissance'=>'22/07/1984'),
    array('nom'=>'Lin Zhu','nomPays'=>'China',
        'marie'=>1,'naissance'=>'01/03/1987'),
    array('nom'=>'Giselle Flowers','nomPays'=>'Nigeria',
        'marie'=>0,'naissance'=>'03/11/1974'),
    array('nom'=>'Stephane Daude','nomPays'=>'France',
        'marie'=>1,'naissance'=>'31/12/1996'),
    array('nom'=>'Emerson Rosa','nomPays'=>'Laos',
            'marie'=>1,'naissance'=>'21/12/1988'),
    array('nom'=>'Jorden Mccall','nomPays'=>'Bahrain',
            'marie'=>1,'naissance'=>'02/08/1970'),
    array('nom'=>'Stephen Vasquez','nomPays'=>'Palau',
            'marie'=>0,'naissance'=>'24/06/1988'),
    array('nom'=>'Martin Bishop','nomPays'=>'Bolivia',
            'marie'=>1,'naissance'=>'28/01/1967'),
    array('nom'=>'Rama Siga','nomPays'=>'Senegal',
            'marie'=>0,'naissance'=>'19/11/1994'),
    array('nom'=>'Brody Christian','nomPays'=>'Burkina Faso',
            'marie'=>1,'naissance'=>'07/03/1977'),
    array('nom'=>'Ruth Roman','nomPays'=>'Solomon Islands',
            'marie'=>1,'naissance'=>'24/07/1978'),
    array('nom'=>'Gemma Guy','nomPays'=>'Lithuania',
            'marie'=>0,'naissance'=>'01/10/1989'),
    array('nom'=>'Elijah Copeland','nomPays'=>'Maldives',
            'marie'=>1,'naissance'=>'26/05/1970'),
    array('nom'=>'Lance Curry','nomPays'=>'Belarus',
            'marie'=>0,'naissance'=>'31/05/1994'),
    array('nom'=>'Forrest Battle','nomPays'=>'Korea, North',
            'marie'=>0,'naissance'=>'05/02/1971'),
    array('nom'=>'Eric Glass','nomPays'=>'Lebanon',
            'marie'=>0,'naissance'=>'19/03/1987'),
    array('nom'=>'Brent Mercado','nomPays'=>'Nepal',
            'marie'=>1,'naissance'=>'17/01/1995'),
    array('nom'=>'Clayton Poole','nomPays'=>'Mali',
            'marie'=>0,'naissance'=>'27/04/1988'),
    array('nom'=>'Rhoda Meyers','nomPays'=>'Cambodia',
            'marie'=>1,'naissance'=>'19/02/1983'),
    array('nom'=>'Sokhna Khoni','nomPays'=>'Senegal',
            'marie'=>1,'naissance'=>'04/10/1989'),
    array('nom'=>'Heather Acosta','nomPays'=>'Samoa',
            'marie'=>1,'naissance'=>'21/01/1974'),
    array('nom'=>'Martin Allison','nomPays'=>'American Samoa',
            'marie'=>0,'naissance'=>'27/11/1996'),
    array('nom'=>'Damon Mills','nomPays'=>'Saint Martin',
            'marie'=>0,'naissance'=>'10/04/1985'),
    array('nom'=>'Baxter Jacobs','nomPays'=>'United States',
            'marie'=>1,'naissance'=>'20/04/1976'),
    array('nom'=>'Jayme Herrera','nomPays'=>'Botswana',
            'marie'=>0,'naissance'=>'13/02/1973'),
    array('nom'=>'Justin Sparks','nomPays'=>'Austria',
            'marie'=>0,'naissance'=>'04/03/1986'),
    array('nom'=>'Phillip Macias','nomPays'=>'Martinique',
            'marie'=>1,'naissance'=>'24/09/1969'),
    array('nom'=>'Althea Bonner','nomPays'=>'Burkina Faso',
            'marie'=>0,'naissance'=>'02/08/1986'),
    array('nom'=>'Melinda Nolan','nomPays'=>'Jersey',
            'marie'=>0,'naissance'=>'14/03/1983'),
    array('nom'=>'Salvador King','nomPays'=>'Iraq',
            'marie'=>0,'naissance'=>'01/10/1976'),
    array('nom'=>'Allistair Winters','nomPays'=>'Kuwait',
            'marie'=>1,'naissance'=>'19/03/1987'),
    array('nom'=>'Roary Golden','nomPays'=>'France',
            'marie'=>1,'naissance'=>'19/09/1995'),
    array('nom'=>'Idola Cantrell','nomPays'=>'Senegal',
            'marie'=>1,'naissance'=>'16/07/1992'),
    array('nom'=>'Chadwick Conrad','nomPays'=>'Puerto Rico',
            'marie'=>1,'naissance'=>'27/02/1997'),
    array('nom'=>'Kiona Huber','nomPays'=>'Czech Republic',
            'marie'=>1,'naissance'=>'26/10/1988'),
    array('nom'=>'Wesley Sloan','nomPays'=>'South Africa',
            'marie'=>1,'naissance'=>'01/12/1991'),
    array('nom'=>'Timothy Hall','nomPays'=>'Estonia',
            'marie'=>0,'naissance'=>'08/08/1991'),
    array('nom'=>'Haviva Peterson','nomPays'=>'Romania',
            'marie'=>1,'naissance'=>'12/01/1974'),
    array('nom'=>'Sylvia Cameron','nomPays'=>'Myanmar',
            'marie'=>0,'naissance'=>'27/01/1970'),
    array('nom'=>'Vernon Russell','nomPays'=>'Micronesia',
            'marie'=>1,'naissance'=>'10/02/1975'),
    array('nom'=>'Kadeem David','nomPays'=>'Morocco',
            'marie'=>0,'naissance'=>'13/12/1987'),
    array('nom'=>'Kylynn Odom','nomPays'=>'Martinique',
            'marie'=>1,'naissance'=>'01/09/1988'),
    array('nom'=>'Jolene Hopper','nomPays'=>'Christmas Island',
            'marie'=>0,'naissance'=>'06/04/1977'),
    array('nom'=>'Anika Foreman','nomPays'=>'Korea, South',
            'marie'=>1,'naissance'=>'12/02/1995'),
    array('nom'=>'Donovan Sullivan','nomPays'=>'Faroe Islands',
            'marie'=>1,'naissance'=>'04/01/1974'),
    array('nom'=>'Yen Stout','nomPays'=>'Nicaragua',
            'marie'=>0,'naissance'=>'19/09/1978'),
    array('nom'=>'Wesley Mcdonald','nomPays'=>'Viet Nam',
            'marie'=>0,'naissance'=>'09/07/1987'),
    array('nom'=>'Gloria English','nomPays'=>'Hungary',
            'marie'=>1,'naissance'=>'05/12/1965'),
    array('nom'=>'Lamar Avila','nomPays'=>'Chad',
            'marie'=>0,'naissance'=>'06/12/1983'),
    array('nom'=>'Barclay Hutchinson','nomPays'=>'Mauritania',
            'marie'=>0,'naissance'=>'29/05/1978'),
    array('nom'=>'Chaim Bond','nomPays'=>'Puerto Rico',
            'marie'=>1,'naissance'=>'14/07/1987'),
    array('nom'=>'Wing Carroll','nomPays'=>'Anguilla',
            'marie'=>1,'naissance'=>'03/11/1990'),
    array('nom'=>'Christian Sullivan','nomPays'=>'Libya',
            'marie'=>1,'naissance'=>'27/02/1980'),
    array('nom'=>'Inez Mathews','nomPays'=>'Cyprus',
            'marie'=>1,'naissance'=>'02/06/1969'),
    array('nom'=>'Gil Maldonado','nomPays'=>'Senegal',
        'marie'=>1,'naissance'=>'23/06/1969'),
    array('nom'=>'Darius Poole','nomPays'=>'Estonia',
            'marie'=>0,'naissance'=>'19/11/1992'),
    array('nom'=>'Stuart Mcdaniel','nomPays'=>'Uruguay',
            'marie'=>0,'naissance'=>'11/10/1995'),
    array('nom'=>'Darrel Key','nomPays'=>'Switzerland',
            'marie'=>1,'naissance'=>'16/02/1983'),
    array('nom'=>'Jolie Mcfarland','nomPays'=>'Afghanistan',
            'marie'=>1,'naissance'=>'26/12/1965'),
    array('nom'=>'Larissa Fox','nomPays'=>'Timor-Leste',
            'marie'=>0,'naissance'=>'01/12/1967'),
    array('nom'=>'Fitzgerald Mayo','nomPays'=>'Suriname',
            'marie'=>1,'naissance'=>'25/04/1970'),
    array('nom'=>'Warren Mcguire','nomPays'=>'Cameroon',
            'marie'=>1,'naissance'=>'19/03/1969'),
    array('nom'=>'Colin Marks','nomPays'=>'Honduras',
            'marie'=>1,'naissance'=>'02/05/1985'),
    array('nom'=>'Brielle Sears','nomPays'=>'Norway',
            'marie'=>0,'naissance'=>'27/02/1979'),
    array('nom'=>'Elaine Holman','nomPays'=>'Cayman Islands',
            'marie'=>1,'naissance'=>'16/06/1969'),
    array('nom'=>'Jin Bonner','nomPays'=>'Seychelles',
            'marie'=>0,'naissance'=>'02/09/1996'),
    array('nom'=>'Ulysses Mccullough','nomPays'=>'Nauru',
            'marie'=>1,'naissance'=>'16/06/1971'),
    array('nom'=>'Xerxes Mccray','nomPays'=>'Hungary',
            'marie'=>1,'naissance'=>'12/12/1987'),
    array('nom'=>'Kirestin Mann','nomPays'=>'Sweden',
            'marie'=>0,'naissance'=>'01/08/1970'),
    array('nom'=>'Allistair Ward','nomPays'=>'Laos',
            'marie'=>0,'naissance'=>'21/04/1977'),
    array('nom'=>'Brennan Mccarty','nomPays'=>'Tuvalu',
            'marie'=>0,'naissance'=>'08/11/1993'),
    array('nom'=>'Camille Fulton','nomPays'=>'Senegal',
            'marie'=>0,'naissance'=>'20/05/1976'),
    array('nom'=>'Leandra Serrano','nomPays'=>'India',
            'marie'=>1,'naissance'=>'23/12/1990'),
    array('nom'=>'Russell Zamora','nomPays'=>'Niger',
            'marie'=>0,'naissance'=>'10/02/1980'),
    array('nom'=>'Hermione Mcconnell','nomPays'=>'Philippines',
            'marie'=>0,'naissance'=>'23/09/1978'),
    array('nom'=>'Alvin Joyce','nomPays'=>'Comoros',
            'marie'=>1,'naissance'=>'15/01/1984'),
    array('nom'=>'Imani Goff','nomPays'=>'Nicaragua',
            'marie'=>1,'naissance'=>'30/01/1994'),
    array('nom'=>'Alan Hoover','nomPays'=>'Greenland',
            'marie'=>1,'naissance'=>'04/09/1971'),
    array('nom'=>'Robert Cantu','nomPays'=>'Western Sahara',
            'marie'=>1,'naissance'=>'13/10/1985')
);

$listPays = [];
$i=1;
$listPays[0] = '';
foreach ($bdd as &$person){
    if(!in_array($person['nomPays'], $listPays)){
        $listPays[$i] = $person['nomPays'];
        $person['pays'] = $i;
        $i++;
    }
    else{
        $person['pays'] = array_search($person['nomPays'], $listPays);
    }
}
unset($listPays);

echo json_encode($bdd);